export { AiPdmRoleCapabilityRepositoryError } from '@/lib/repositories/ai-pdm-role-capability-repository'

export const AI_PDM_ROLE_CAPABILITY_ERROR_CODES = [
  'ORGMASTER_UNAVAILABLE', 'ORGMASTER_CONTRACT_INVALID', 'ORGMASTER_REVISION_CONFLICT',
  'ORGMASTER_CATALOG_MISMATCH', 'ORGMASTER_OUTCOME_UNKNOWN', 'COMMAND_STILL_PROCESSING',
  'COMMAND_NOT_FOUND', 'REQUEST_HASH_MISMATCH',
] as const
