export const NUMBERING_PAGE_PERMISSION_CODES = [
  "numbering.request",
  "numbering.search",
  "numbering.drawings.view",
  "numbering.approvals",
  "numbering.tasks",
  "numbering.reports",
  "settings.admin_matrix"
] as const;

export const NUMBERING_ACTION_PERMISSION_CODES = [
  "numbering.workspace.view",
  "numbering.workspace.create",
  "numbering.workspace.update",
  "numbering.workspace.cancel",
  "numbering.candidate.acquire",
  "numbering.candidate.recycle",
  "numbering.candidate.review.submit",
  "numbering.candidate.review.withdraw",
  "numbering.candidate.review.decide",
  "numbering.publish",
  "transfer.package.view",
  "transfer.package.create",
  "transfer.package.update",
  "transfer.package.review.submit",
  "transfer.package.review.withdraw",
  "transfer.package.review.decide",
  "transfer.package.publish",
  "handoff.published.view",
  "numbering.create",
  "numbering.draft.update",
  "numbering.draft.obsolete",
  "numbering.draft.admin_confirm",
  "numbering.duplicate_check",
  "numbering.link_variant",
  "numbering.approval.request",
  "numbering.approval.batch.create",
  "numbering.approval.batch.decide",
  "numbering.approval.batch.resubmit",
  "numbering.export.create",
  "numbering.audit_report.generate",
  "numbering.task.update",
  "numbering.notification.update",
  "numbering.attachments.manage",
  "numbering.recognition.run",
  "numbering.recognition.review",
  "numbering.recognition.formalize",
  "pdm.comment.create",
  "pdm.advice.create",
  "settings.admin_matrix",
  "update_name",
  "update_spec",
  "obsolete_part_number",
  "obsolete_ma_drawing",
  "obsolete_part_root",
  "merge_part_number",
  "release_missing_ma_confirm",
  "release",
  "post_release_change",
  "same_drawing_variant_after_release",
  "main_drawing_restore"
] as const;

export const NUMBERING_NAV_PERMISSION_BY_PATH: Record<string, string> = {
  "/numbering/request": "numbering.request",
  "/numbering/search": "numbering.search",
  "/numbering/drawings": "numbering.drawings.view",
  "/numbering/part-drafts": "numbering.tasks",
  "/parts": "numbering.search",
  "/approvals": "numbering.approvals",
  "/numbering/approvals": "numbering.approvals",
  "/numbering/change-reviews": "numbering.approvals",
  "/settings/accounts": "settings.admin_matrix",
  "/settings/account-invitations": "settings.admin_matrix",
  "/settings": "settings.admin_matrix"
};
