-- AI PDM PostgreSQL / Supabase initial schema
-- Generated by scripts/generate-postgres-migration.mjs
-- Keep application-generated TEXT ids to preserve compatibility with the current SQLite data model.

BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  email TEXT UNIQUE,
  password_hash TEXT,
  role TEXT NOT NULL CHECK (role IN ('Engineer', 'R&D Manager', 'Admin')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS system_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by TEXT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS items (
  id TEXT PRIMARY KEY,
  part_number TEXT NOT NULL UNIQUE,
  part_name TEXT NOT NULL,
  current_revision TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS submissions (
  id TEXT PRIMARY KEY,
  item_id TEXT NOT NULL REFERENCES items(id),
  drawing_number TEXT NOT NULL,
  revision TEXT NOT NULL,
  material TEXT NOT NULL,
  surface_finish TEXT NOT NULL,
  document_type TEXT NOT NULL,
  change_description TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Pending', 'Releasing', 'Released', 'Rejected', 'ReleaseFailed', 'Obsolete')),
  submitted_by TEXT NOT NULL REFERENCES users(id),
  approval_required INTEGER NOT NULL DEFAULT 1 CHECK (approval_required IN (1, 2)),
  released_at TIMESTAMPTZ,
  rejected_at TIMESTAMPTZ,
  reject_reason TEXT,
  release_error TEXT,
  superseded_by_submission_id TEXT REFERENCES submissions(id),
  obsolete_at TIMESTAMPTZ,
  obsolete_by TEXT REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (drawing_number, revision)
);

CREATE TABLE IF NOT EXISTS submission_files (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  file_role TEXT NOT NULL CHECK (file_role IN ('sldprt', 'sldasm', 'slddrw', 'pdf', 'dwg', 'other')),
  original_filename TEXT NOT NULL,
  local_path TEXT NOT NULL,
  gdrive_file_id TEXT,
  gdrive_status TEXT NOT NULL DEFAULT 'none' CHECK (gdrive_status IN ('none', 'uploading', 'uploaded', 'failed', 'moved')),
  sha256 TEXT NOT NULL,
  file_size BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (submission_id, file_role, original_filename)
);

CREATE TABLE IF NOT EXISTS file_references (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  source_file_id TEXT REFERENCES submission_files(id) ON DELETE SET NULL,
  source_filename TEXT NOT NULL,
  source_file_role TEXT NOT NULL CHECK (source_file_role IN ('sldprt', 'sldasm', 'slddrw', 'pdf', 'dwg', 'other')),
  referenced_filename TEXT NOT NULL,
  referenced_part_number TEXT,
  referenced_drawing_number TEXT,
  referenced_revision TEXT,
  reference_type TEXT NOT NULL CHECK (reference_type IN ('assembly_component', 'drawing_model', 'derived', 'unknown')),
  quantity DOUBLE PRECISION NOT NULL DEFAULT 1,
  extraction_method TEXT NOT NULL,
  confidence TEXT NOT NULL CHECK (confidence IN ('high', 'medium', 'low')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bom_headers (
  id TEXT PRIMARY KEY,
  parent_item_id TEXT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  parent_submission_id TEXT NOT NULL UNIQUE REFERENCES submissions(id) ON DELETE CASCADE,
  parent_revision TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft', 'ReleasedSnapshot')),
  source TEXT NOT NULL DEFAULT 'cad_references' CHECK (source IN ('cad_references', 'manual', 'imported')),
  line_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bom_lines (
  id TEXT PRIMARY KEY,
  bom_header_id TEXT NOT NULL REFERENCES bom_headers(id) ON DELETE CASCADE,
  line_no INTEGER NOT NULL,
  child_part_number TEXT NOT NULL,
  child_revision TEXT,
  quantity DOUBLE PRECISION NOT NULL DEFAULT 1 CHECK (quantity > 0),
  source_file_id TEXT REFERENCES submission_files(id) ON DELETE SET NULL,
  source_reference_id TEXT REFERENCES file_references(id) ON DELETE SET NULL,
  source_filename TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (bom_header_id, line_no)
);

CREATE TABLE IF NOT EXISTS release_packages (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL UNIQUE REFERENCES submissions(id) ON DELETE CASCADE,
  package_filename TEXT NOT NULL,
  local_path TEXT NOT NULL,
  sha256 TEXT NOT NULL,
  file_size INTEGER NOT NULL,
  manifest_json JSONB NOT NULL,
  created_by TEXT REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS readonly_shares (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_by TEXT NOT NULL REFERENCES users(id),
  revoked_at TIMESTAMPTZ,
  revoked_by TEXT REFERENCES users(id),
  access_count INTEGER NOT NULL DEFAULT 0,
  last_accessed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS supplier_portal_responses (
  id TEXT PRIMARY KEY,
  share_id TEXT NOT NULL REFERENCES readonly_shares(id) ON DELETE CASCADE,
  submission_id TEXT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  response_kind TEXT NOT NULL CHECK (response_kind IN ('acknowledgement', 'question')),
  supplier_name TEXT NOT NULL,
  supplier_email TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
  closed_by TEXT REFERENCES users(id),
  closed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS procurement_sync_runs (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  target_system TEXT NOT NULL CHECK (target_system IN ('ERP', 'inventory', 'procurement')),
  status TEXT NOT NULL DEFAULT 'sent' CHECK (status IN ('sent', 'acknowledged', 'failed')),
  payload_json JSONB NOT NULL,
  response_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  external_reference TEXT,
  created_by TEXT NOT NULL REFERENCES users(id),
  acknowledged_by TEXT REFERENCES users(id),
  acknowledged_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sandbox_branches (
  id TEXT PRIMARY KEY,
  source_submission_id TEXT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  sandbox_submission_id TEXT NOT NULL UNIQUE REFERENCES submissions(id) ON DELETE CASCADE,
  branch_name TEXT NOT NULL,
  reason TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'promoted', 'closed')),
  created_by TEXT NOT NULL REFERENCES users(id),
  promoted_by TEXT REFERENCES users(id),
  closed_by TEXT REFERENCES users(id),
  merged_by TEXT REFERENCES users(id),
  merge_summary_json TEXT,
  promoted_at TIMESTAMPTZ,
  closed_at TIMESTAMPTZ,
  merged_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (source_submission_id, branch_name)
);

CREATE TABLE IF NOT EXISTS discussion_comments (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  file_id TEXT REFERENCES submission_files(id) ON DELETE SET NULL,
  author_id TEXT NOT NULL REFERENCES users(id),
  body TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved')),
  resolved_by TEXT REFERENCES users(id),
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS review_issues (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  file_id TEXT REFERENCES submission_files(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved')),
  raised_by TEXT NOT NULL REFERENCES users(id),
  assignee_id TEXT REFERENCES users(id),
  resolved_by TEXT REFERENCES users(id),
  resolution TEXT,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS change_requests (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  kind TEXT NOT NULL CHECK (kind IN ('ECR', 'ECO', 'ECN')),
  title TEXT NOT NULL,
  reason TEXT NOT NULL,
  impact TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'approved', 'rejected', 'closed')),
  requested_by TEXT NOT NULL REFERENCES users(id),
  decided_by TEXT REFERENCES users(id),
  decision_comment TEXT,
  decided_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS phase_gate_checks (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  gate_code TEXT NOT NULL CHECK (gate_code IN ('concept', 'design', 'verification', 'release')),
  gate_name TEXT NOT NULL,
  checklist_item TEXT NOT NULL,
  required BOOLEAN NOT NULL DEFAULT true,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'completed', 'waived')),
  created_by TEXT NOT NULL REFERENCES users(id),
  decided_by TEXT REFERENCES users(id),
  decision_comment TEXT,
  decided_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (submission_id, gate_code, checklist_item)
);

CREATE TABLE IF NOT EXISTS pdf_markups (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  file_id TEXT NOT NULL REFERENCES submission_files(id) ON DELETE CASCADE,
  page_number INTEGER NOT NULL CHECK (page_number > 0),
  x_percent NUMERIC NOT NULL CHECK (x_percent >= 0 AND x_percent <= 100),
  y_percent NUMERIC NOT NULL CHECK (y_percent >= 0 AND y_percent <= 100),
  body TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved')),
  author_id TEXT NOT NULL REFERENCES users(id),
  resolved_by TEXT REFERENCES users(id),
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS approval_steps (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  reviewer_id TEXT NOT NULL REFERENCES users(id),
  sequence_no INTEGER NOT NULL DEFAULT 1,
  decision TEXT NOT NULL CHECK (decision IN ('Approved', 'Rejected')),
  comment TEXT,
  decided_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (submission_id, reviewer_id, sequence_no)
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id TEXT PRIMARY KEY,
  submission_id TEXT REFERENCES submissions(id) ON DELETE SET NULL,
  actor_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS llm_conversations (
  id TEXT PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  title TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS llm_messages (
  id TEXT PRIMARY KEY,
  conversation_id TEXT NOT NULL REFERENCES llm_conversations(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_submissions_status_created_at
  ON submissions(status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_submission_files_submission_id
  ON submission_files(submission_id);

CREATE INDEX IF NOT EXISTS idx_file_references_submission_id
  ON file_references(submission_id);

CREATE INDEX IF NOT EXISTS idx_file_references_referenced_part_number
  ON file_references(referenced_part_number);

CREATE INDEX IF NOT EXISTS idx_bom_headers_parent_item_id
  ON bom_headers(parent_item_id);

CREATE INDEX IF NOT EXISTS idx_bom_headers_parent_submission_id
  ON bom_headers(parent_submission_id);

CREATE INDEX IF NOT EXISTS idx_bom_lines_header_id
  ON bom_lines(bom_header_id);

CREATE INDEX IF NOT EXISTS idx_bom_lines_child_part_number
  ON bom_lines(child_part_number);

CREATE INDEX IF NOT EXISTS idx_release_packages_submission_id
  ON release_packages(submission_id);

CREATE INDEX IF NOT EXISTS idx_readonly_shares_submission_id
  ON readonly_shares(submission_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_readonly_shares_token_hash
  ON readonly_shares(token_hash);

CREATE INDEX IF NOT EXISTS idx_supplier_portal_responses_submission_id
  ON supplier_portal_responses(submission_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_supplier_portal_responses_share_id
  ON supplier_portal_responses(share_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_procurement_sync_runs_submission_id
  ON procurement_sync_runs(submission_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_procurement_sync_runs_target_status
  ON procurement_sync_runs(target_system, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sandbox_branches_source_submission_id
  ON sandbox_branches(source_submission_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sandbox_branches_sandbox_submission_id
  ON sandbox_branches(sandbox_submission_id);

CREATE INDEX IF NOT EXISTS idx_discussion_comments_submission_id
  ON discussion_comments(submission_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_discussion_comments_file_id
  ON discussion_comments(file_id);

CREATE INDEX IF NOT EXISTS idx_review_issues_submission_id
  ON review_issues(submission_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_review_issues_file_id
  ON review_issues(file_id);

CREATE INDEX IF NOT EXISTS idx_change_requests_submission_id
  ON change_requests(submission_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_phase_gate_checks_submission_id
  ON phase_gate_checks(submission_id, status, gate_code);

CREATE INDEX IF NOT EXISTS idx_pdf_markups_submission_id
  ON pdf_markups(submission_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_pdf_markups_file_id
  ON pdf_markups(file_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_submission_id
  ON audit_logs(submission_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_submissions_item_id
  ON submissions(item_id);

CREATE INDEX IF NOT EXISTS idx_submissions_submitted_by
  ON submissions(submitted_by);

CREATE INDEX IF NOT EXISTS idx_approval_steps_submission_id
  ON approval_steps(submission_id);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_items_updated_at ON items;
CREATE TRIGGER trg_items_updated_at
BEFORE UPDATE ON items
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_submissions_updated_at ON submissions;
CREATE TRIGGER trg_submissions_updated_at
BEFORE UPDATE ON submissions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_llm_conversations_updated_at ON llm_conversations;
CREATE TRIGGER trg_llm_conversations_updated_at
BEFORE UPDATE ON llm_conversations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_bom_headers_updated_at ON bom_headers;
CREATE TRIGGER trg_bom_headers_updated_at
BEFORE UPDATE ON bom_headers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_readonly_shares_updated_at ON readonly_shares;
CREATE TRIGGER trg_readonly_shares_updated_at
BEFORE UPDATE ON readonly_shares
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_supplier_portal_responses_updated_at ON supplier_portal_responses;
CREATE TRIGGER trg_supplier_portal_responses_updated_at
BEFORE UPDATE ON supplier_portal_responses
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_procurement_sync_runs_updated_at ON procurement_sync_runs;
CREATE TRIGGER trg_procurement_sync_runs_updated_at
BEFORE UPDATE ON procurement_sync_runs
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_sandbox_branches_updated_at ON sandbox_branches;
CREATE TRIGGER trg_sandbox_branches_updated_at
BEFORE UPDATE ON sandbox_branches
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_discussion_comments_updated_at ON discussion_comments;
CREATE TRIGGER trg_discussion_comments_updated_at
BEFORE UPDATE ON discussion_comments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_review_issues_updated_at ON review_issues;
CREATE TRIGGER trg_review_issues_updated_at
BEFORE UPDATE ON review_issues
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_change_requests_updated_at ON change_requests;
CREATE TRIGGER trg_change_requests_updated_at
BEFORE UPDATE ON change_requests
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_phase_gate_checks_updated_at ON phase_gate_checks;
CREATE TRIGGER trg_phase_gate_checks_updated_at
BEFORE UPDATE ON phase_gate_checks
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_pdf_markups_updated_at ON pdf_markups;
CREATE TRIGGER trg_pdf_markups_updated_at
BEFORE UPDATE ON pdf_markups
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;
