-- AI PDM Supabase RLS baseline plan
-- Generated by scripts/generate-postgres-migration.mjs
-- This intentionally denies direct Data API access until explicit policies are designed.
-- Future policies must use auth.uid() or signed app metadata, never user-editable metadata.

BEGIN;
SET search_path = public;

DO $$
DECLARE
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['users', 'system_settings', 'items', 'submissions', 'submission_files', 'file_references', 'bom_headers', 'bom_lines', 'item_locks', 'release_packages', 'readonly_shares', 'supplier_portal_responses', 'procurement_sync_runs', 'sandbox_branches', 'discussion_comments', 'review_issues', 'change_requests', 'phase_gate_checks', 'pdf_markups', 'approval_steps', 'approval_matrix_requirements', 'audit_logs', 'llm_conversations', 'llm_messages']
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY', table_name);
  END LOOP;
END $$;

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;

COMMENT ON SCHEMA public IS 'AI PDM baseline: direct Data API access is denied by default. Application access must go through the server-side PDM API until explicit RLS policies are approved.';

COMMIT;
