-- Initial AI_PDM public schema converted from SQLite
-- Source: db/postgres/001_initial_schema.sql
-- Source SHA-256: ec91860f889d306a7f9e2a3fc3d4c702d8790c6a1953ce481276fce7e142e7aa
-- This file is synchronized by npm.cmd run supabase:migrations:sync.

-- AI PDM PostgreSQL / Supabase initial schema
-- Generated by scripts/generate-postgres-migration.mjs from db/schema.sql
-- Keep application-generated TEXT ids to preserve compatibility with the current SQLite data model.

BEGIN;
SET search_path = public;

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  email TEXT UNIQUE,
  password_hash TEXT,
  role TEXT NOT NULL CHECK (role IN ('Engineer', 'R&D Manager', 'Admin', 'Manufacturing', 'Procurement')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS system_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by TEXT,
  FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS items (
  id TEXT PRIMARY KEY,
  part_number TEXT NOT NULL UNIQUE,
  part_name TEXT NOT NULL,
  current_revision TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS submissions (
  id TEXT PRIMARY KEY,
  item_id TEXT NOT NULL,
  drawing_number TEXT NOT NULL,
  revision TEXT NOT NULL,
  product_line TEXT NOT NULL DEFAULT '',
  customer TEXT NOT NULL DEFAULT '',
  project_code TEXT NOT NULL DEFAULT '',
  process_name TEXT NOT NULL DEFAULT '',
  machine TEXT NOT NULL DEFAULT '',
  material TEXT NOT NULL,
  surface_finish TEXT NOT NULL,
  document_type TEXT NOT NULL,
  change_description TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Pending', 'Releasing', 'Released', 'Rejected', 'ReleaseFailed', 'Obsolete')),
  submitted_by TEXT NOT NULL,
  approval_required INTEGER NOT NULL DEFAULT 1 CHECK (approval_required IN (1, 2)),
  released_at TIMESTAMPTZ,
  rejected_at TIMESTAMPTZ,
  reject_reason TEXT,
  release_error TEXT,
  superseded_by_submission_id TEXT,
  obsolete_at TIMESTAMPTZ,
  obsolete_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (item_id) REFERENCES items(id),
  FOREIGN KEY (submitted_by) REFERENCES users(id),
  FOREIGN KEY (superseded_by_submission_id) REFERENCES submissions(id),
  FOREIGN KEY (obsolete_by) REFERENCES users(id),
  UNIQUE (drawing_number, revision)
);

CREATE TABLE IF NOT EXISTS submission_files (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL,
  file_role TEXT NOT NULL CHECK (file_role IN ('sldprt', 'sldasm', 'slddrw', 'pdf', 'dwg', 'other')),
  original_filename TEXT NOT NULL,
  local_path TEXT NOT NULL,
  gdrive_file_id TEXT,
  gdrive_status TEXT NOT NULL DEFAULT 'none' CHECK (gdrive_status IN ('none', 'uploading', 'uploaded', 'failed', 'moved')),
  sha256 TEXT NOT NULL,
  file_size BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
  UNIQUE (submission_id, file_role, original_filename)
);

CREATE TABLE IF NOT EXISTS file_references (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL,
  source_file_id TEXT,
  source_filename TEXT NOT NULL,
  source_file_role TEXT NOT NULL CHECK (source_file_role IN ('sldprt', 'sldasm', 'slddrw', 'pdf', 'dwg', 'other')),
  referenced_filename TEXT NOT NULL,
  referenced_part_number TEXT,
  referenced_drawing_number TEXT,
  referenced_revision TEXT,
  reference_type TEXT NOT NULL CHECK (reference_type IN ('assembly_component', 'drawing_model', 'derived', 'unknown')),
  quantity DOUBLE PRECISION NOT NULL DEFAULT 1,
  extraction_method TEXT NOT NULL,
  confidence TEXT NOT NULL CHECK (confidence IN ('high', 'medium', 'low')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
  FOREIGN KEY (source_file_id) REFERENCES submission_files(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS bom_headers (
  id TEXT PRIMARY KEY,
  parent_item_id TEXT NOT NULL,
  parent_submission_id TEXT NOT NULL UNIQUE,
  parent_revision TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft', 'ReleasedSnapshot')),
  source TEXT NOT NULL DEFAULT 'cad_references' CHECK (source IN ('cad_references', 'manual', 'imported')),
  line_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (parent_item_id) REFERENCES items(id) ON DELETE CASCADE,
  FOREIGN KEY (parent_submission_id) REFERENCES submissions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bom_lines (
  id TEXT PRIMARY KEY,
  bom_header_id TEXT NOT NULL,
  line_no INTEGER NOT NULL,
  child_part_number TEXT NOT NULL,
  child_revision TEXT,
  quantity DOUBLE PRECISION NOT NULL DEFAULT 1 CHECK (quantity > 0),
  source_file_id TEXT,
  source_reference_id TEXT,
  source_filename TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (bom_header_id) REFERENCES bom_headers(id) ON DELETE CASCADE,
  FOREIGN KEY (source_file_id) REFERENCES submission_files(id) ON DELETE SET NULL,
  FOREIGN KEY (source_reference_id) REFERENCES file_references(id) ON DELETE SET NULL,
  UNIQUE (bom_header_id, line_no)
);

CREATE TABLE IF NOT EXISTS bom_drafts (
  id TEXT PRIMARY KEY,
  parent_item_id TEXT NOT NULL,
  parent_submission_id TEXT NOT NULL,
  parent_revision TEXT NOT NULL,
  draft_name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft', 'PendingReview', 'Rejected', 'Released', 'Obsolete', 'Archived')),
  source TEXT NOT NULL DEFAULT 'cad_reference' CHECK (source IN ('cad_reference', 'solidworks_xls', 'manual')),
  is_active INTEGER NOT NULL DEFAULT 0 CHECK (is_active IN (0, 1)),
  line_count INTEGER NOT NULL DEFAULT 0,
  review_attempt INTEGER NOT NULL DEFAULT 0,
  created_by TEXT,
  updated_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (parent_item_id) REFERENCES items(id) ON DELETE CASCADE,
  FOREIGN KEY (parent_submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS bom_lines_tree (
  id TEXT PRIMARY KEY,
  bom_draft_id TEXT NOT NULL,
  parent_line_id TEXT,
  node_type TEXT NOT NULL CHECK (node_type IN ('item', 'group')),
  item_id TEXT,
  part_number TEXT,
  revision TEXT,
  group_name TEXT,
  quantity DOUBLE PRECISION CHECK (quantity IS NULL OR quantity > 0),
  sequence_no INTEGER NOT NULL,
  source TEXT NOT NULL DEFAULT 'cad_reference' CHECK (source IN ('cad_reference', 'solidworks_xls', 'manual')),
  source_priority INTEGER NOT NULL DEFAULT 10,
  source_ref_id TEXT,
  source_filename TEXT,
  created_by TEXT,
  updated_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (
    (node_type = 'item' AND part_number IS NOT NULL AND trim(part_number) <> '' AND quantity IS NOT NULL)
    OR
    (node_type = 'group' AND group_name IS NOT NULL AND trim(group_name) <> '' AND quantity IS NULL)
  ),
  FOREIGN KEY (bom_draft_id) REFERENCES bom_drafts(id) ON DELETE CASCADE,
  FOREIGN KEY (parent_line_id) REFERENCES bom_lines_tree(id) ON DELETE CASCADE,
  FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS bom_import_profiles (
  id TEXT PRIMARY KEY,
  profile_name TEXT NOT NULL,
  source_type TEXT NOT NULL DEFAULT 'solidworks_xls' CHECK (source_type IN ('solidworks_xls')),
  version TEXT NOT NULL,
  mapping_json TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (profile_name, version)
);

CREATE TABLE IF NOT EXISTS bom_import_jobs (
  id TEXT PRIMARY KEY,
  bom_draft_id TEXT,
  parent_submission_id TEXT NOT NULL,
  import_profile_id TEXT NOT NULL,
  source_asset_id TEXT,
  original_filename TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Staged' CHECK (status IN ('Staged', 'Imported', 'Rejected', 'Failed')),
  row_count INTEGER NOT NULL DEFAULT 0,
  error_json TEXT,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (bom_draft_id) REFERENCES bom_drafts(id) ON DELETE SET NULL,
  FOREIGN KEY (parent_submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
  FOREIGN KEY (import_profile_id) REFERENCES bom_import_profiles(id),
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS bom_edit_events (
  id TEXT PRIMARY KEY,
  bom_draft_id TEXT NOT NULL,
  actor_id TEXT,
  event_type TEXT NOT NULL,
  before_json TEXT,
  after_json TEXT,
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (bom_draft_id) REFERENCES bom_drafts(id) ON DELETE CASCADE,
  FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS bom_review_requests (
  id TEXT PRIMARY KEY,
  bom_draft_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PendingReview' CHECK (status IN ('PendingReview', 'Approved', 'Rejected', 'Cancelled')),
  submitted_by TEXT NOT NULL,
  reviewed_by TEXT,
  change_reason TEXT NOT NULL,
  decision_reason TEXT,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reviewed_at TIMESTAMPTZ,
  FOREIGN KEY (bom_draft_id) REFERENCES bom_drafts(id) ON DELETE CASCADE,
  FOREIGN KEY (submitted_by) REFERENCES users(id),
  FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS bom_release_snapshots (
  id TEXT PRIMARY KEY,
  bom_draft_id TEXT NOT NULL,
  parent_item_id TEXT NOT NULL,
  parent_submission_id TEXT NOT NULL,
  parent_revision TEXT NOT NULL,
  line_snapshot_json TEXT NOT NULL,
  line_count INTEGER NOT NULL DEFAULT 0,
  released_by TEXT NOT NULL,
  released_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  obsolete_at TIMESTAMPTZ,
  obsolete_by TEXT,
  FOREIGN KEY (bom_draft_id) REFERENCES bom_drafts(id),
  FOREIGN KEY (parent_item_id) REFERENCES items(id),
  FOREIGN KEY (parent_submission_id) REFERENCES submissions(id),
  FOREIGN KEY (released_by) REFERENCES users(id),
  FOREIGN KEY (obsolete_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS item_locks (
  id TEXT PRIMARY KEY,
  item_id TEXT NOT NULL,
  locked_by TEXT NOT NULL,
  lock_reason TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  released_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
  FOREIGN KEY (locked_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS release_packages (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL UNIQUE,
  package_filename TEXT NOT NULL,
  local_path TEXT NOT NULL,
  sha256 TEXT NOT NULL,
  file_size BIGINT NOT NULL,
  manifest_json JSONB NOT NULL,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS readonly_shares (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_by TEXT NOT NULL,
  revoked_at TIMESTAMPTZ,
  revoked_by TEXT,
  access_count INTEGER NOT NULL DEFAULT 0,
  last_accessed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (revoked_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS supplier_portal_responses (
  id TEXT PRIMARY KEY,
  share_id TEXT NOT NULL,
  submission_id TEXT NOT NULL,
  response_kind TEXT NOT NULL CHECK (response_kind IN ('acknowledgement', 'question')),
  supplier_name TEXT NOT NULL,
  supplier_email TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
  closed_by TEXT,
  closed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (share_id) REFERENCES readonly_shares(id) ON DELETE CASCADE,
  FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
  FOREIGN KEY (closed_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS procurement_sync_runs (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL,
  target_system TEXT NOT NULL CHECK (target_system IN ('ERP', 'inventory', 'procurement')),
  status TEXT NOT NULL DEFAULT 'sent' CHECK (status IN ('sent', 'acknowledged', 'failed')),
  payload_json JSONB NOT NULL,
  response_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  external_reference TEXT,
  created_by TEXT NOT NULL,
  acknowledged_by TEXT,
  acknowledged_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (acknowledged_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS sandbox_branches (
  id TEXT PRIMARY KEY,
  source_submission_id TEXT NOT NULL,
  sandbox_submission_id TEXT NOT NULL UNIQUE,
  branch_name TEXT NOT NULL,
  reason TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'promoted', 'closed')),
  created_by TEXT NOT NULL,
  promoted_by TEXT,
  closed_by TEXT,
  merged_by TEXT,
  merge_summary_json JSONB,
  promoted_at TIMESTAMPTZ,
  closed_at TIMESTAMPTZ,
  merged_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (source_submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
  FOREIGN KEY (sandbox_submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (promoted_by) REFERENCES users(id),
  FOREIGN KEY (closed_by) REFERENCES users(id),
  FOREIGN KEY (merged_by) REFERENCES users(id),
  UNIQUE (source_submission_id, branch_name)
);

CREATE TABLE IF NOT EXISTS discussion_comments (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL,
  file_id TEXT,
  author_id TEXT NOT NULL,
  body TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved')),
  resolved_by TEXT,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
  FOREIGN KEY (file_id) REFERENCES submission_files(id) ON DELETE SET NULL,
  FOREIGN KEY (author_id) REFERENCES users(id),
  FOREIGN KEY (resolved_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS review_issues (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL,
  file_id TEXT,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved')),
  raised_by TEXT NOT NULL,
  assignee_id TEXT,
  resolved_by TEXT,
  resolution TEXT,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
  FOREIGN KEY (file_id) REFERENCES submission_files(id) ON DELETE SET NULL,
  FOREIGN KEY (raised_by) REFERENCES users(id),
  FOREIGN KEY (assignee_id) REFERENCES users(id),
  FOREIGN KEY (resolved_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS change_requests (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('ECR', 'ECO', 'ECN')),
  title TEXT NOT NULL,
  reason TEXT NOT NULL,
  impact TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'approved', 'rejected', 'closed')),
  requested_by TEXT NOT NULL,
  decided_by TEXT,
  decision_comment TEXT,
  decided_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
  FOREIGN KEY (requested_by) REFERENCES users(id),
  FOREIGN KEY (decided_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS phase_gate_checks (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL,
  gate_code TEXT NOT NULL CHECK (gate_code IN ('concept', 'design', 'verification', 'release')),
  gate_name TEXT NOT NULL,
  checklist_item TEXT NOT NULL,
  required INTEGER NOT NULL DEFAULT 1 CHECK (required IN (0, 1)),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'completed', 'waived')),
  created_by TEXT NOT NULL,
  decided_by TEXT,
  decision_comment TEXT,
  decided_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (decided_by) REFERENCES users(id),
  UNIQUE (submission_id, gate_code, checklist_item)
);

CREATE TABLE IF NOT EXISTS pdf_markups (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL,
  file_id TEXT NOT NULL,
  page_number INTEGER NOT NULL CHECK (page_number > 0),
  x_percent DOUBLE PRECISION NOT NULL CHECK (x_percent >= 0 AND x_percent <= 100),
  y_percent DOUBLE PRECISION NOT NULL CHECK (y_percent >= 0 AND y_percent <= 100),
  body TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved')),
  author_id TEXT NOT NULL,
  resolved_by TEXT,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
  FOREIGN KEY (file_id) REFERENCES submission_files(id) ON DELETE CASCADE,
  FOREIGN KEY (author_id) REFERENCES users(id),
  FOREIGN KEY (resolved_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS approval_steps (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL,
  reviewer_id TEXT NOT NULL,
  sequence_no INTEGER NOT NULL DEFAULT 1,
  decision TEXT NOT NULL CHECK (decision IN ('Approved', 'Rejected')),
  comment TEXT,
  decided_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
  FOREIGN KEY (reviewer_id) REFERENCES users(id),
  UNIQUE (submission_id, reviewer_id, sequence_no)
);

CREATE TABLE IF NOT EXISTS approval_matrix_requirements (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL,
  required_role TEXT NOT NULL CHECK (required_role IN ('R&D Manager', 'Admin')),
  min_count INTEGER NOT NULL DEFAULT 1 CHECK (min_count BETWEEN 1 AND 3),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'satisfied', 'waived')),
  created_by TEXT NOT NULL,
  decided_by TEXT,
  decision_comment TEXT,
  decided_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (decided_by) REFERENCES users(id),
  UNIQUE (submission_id, required_role)
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id TEXT PRIMARY KEY,
  submission_id TEXT,
  actor_id TEXT,
  action TEXT NOT NULL,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS numbering_sequences (
  sequence_key TEXT PRIMARY KEY,
  next_value INTEGER NOT NULL CHECK (next_value > 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS numbering_rule_versions (
  id TEXT PRIMARY KEY,
  rule_code TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('draft', 'active', 'retired')),
  effective_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  retired_at TIMESTAMPTZ,
  rule_json TEXT NOT NULL DEFAULT '{}',
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS part_roots (
  id TEXT PRIMARY KEY,
  root_code TEXT NOT NULL UNIQUE,
  core_name TEXT NOT NULL,
  item_kind TEXT NOT NULL CHECK (item_kind IN ('purchased', 'manufactured', 'outsourced', 'shared', 'custom')),
  development_phase TEXT NOT NULL DEFAULT 'EVT' CHECK (development_phase IN ('EVT', 'DVT', 'PVT', 'Release', 'ECR')),
  record_status TEXT NOT NULL DEFAULT 'Draft' CHECK (record_status IN ('Draft', 'NeedInfo', 'Active', 'PendingReview', 'Released', 'Rejected', 'Obsolete', 'Merged', 'EVTDisabled', 'PendingAdminConfirm', 'MainDrawingInvalid')),
  rule_version_id TEXT NOT NULL DEFAULT 'numbering-rule-v1',
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (rule_version_id) REFERENCES numbering_rule_versions(id),
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS part_numbers (
  id TEXT PRIMARY KEY,
  part_root_id TEXT NOT NULL,
  part_number TEXT NOT NULL UNIQUE,
  sequence_no INTEGER NOT NULL CHECK (sequence_no >= 0),
  sequence_code TEXT NOT NULL,
  part_name TEXT NOT NULL,
  item_kind TEXT NOT NULL CHECK (item_kind IN ('purchased', 'manufactured', 'outsourced', 'shared', 'custom')),
  is_universal INTEGER NOT NULL DEFAULT 0 CHECK (is_universal IN (0, 1)),
  bom_usage_policy TEXT NOT NULL DEFAULT 'undecided' CHECK (bom_usage_policy IN ('undecided', 'not_required', 'available', 'restricted', 'obsolete')),
  custom_specification TEXT,
  development_phase TEXT NOT NULL DEFAULT 'EVT' CHECK (development_phase IN ('EVT', 'DVT', 'PVT', 'Release', 'ECR')),
  record_status TEXT NOT NULL DEFAULT 'Draft' CHECK (record_status IN ('Draft', 'NeedInfo', 'Active', 'PendingReview', 'Released', 'Rejected', 'Obsolete', 'Merged', 'EVTDisabled', 'PendingAdminConfirm', 'MainDrawingInvalid')),
  universal_reason TEXT,
  rule_version_id TEXT NOT NULL DEFAULT 'numbering-rule-v1',
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (part_root_id) REFERENCES part_roots(id) ON DELETE CASCADE,
  FOREIGN KEY (rule_version_id) REFERENCES numbering_rule_versions(id),
  FOREIGN KEY (created_by) REFERENCES users(id),
  UNIQUE (part_root_id, sequence_code)
);

CREATE TABLE IF NOT EXISTS drawing_numbers (
  id TEXT PRIMARY KEY,
  part_root_id TEXT NOT NULL,
  drawing_number TEXT NOT NULL UNIQUE,
  purpose_code TEXT NOT NULL CHECK (purpose_code IN ('MA', 'OT')),
  purpose_description TEXT NOT NULL DEFAULT '',
  sequence_no INTEGER NOT NULL CHECK (sequence_no > 0),
  is_primary_manufacturing INTEGER NOT NULL DEFAULT 0 CHECK (is_primary_manufacturing IN (0, 1)),
  development_phase TEXT NOT NULL DEFAULT 'EVT' CHECK (development_phase IN ('EVT', 'DVT', 'PVT', 'Release', 'ECR')),
  record_status TEXT NOT NULL DEFAULT 'Draft' CHECK (record_status IN ('Draft', 'NeedInfo', 'Active', 'PendingReview', 'Released', 'Rejected', 'Obsolete', 'Merged', 'EVTDisabled', 'PendingAdminConfirm', 'MainDrawingInvalid')),
  rule_version_id TEXT NOT NULL DEFAULT 'numbering-rule-v1',
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (part_root_id) REFERENCES part_roots(id) ON DELETE CASCADE,
  FOREIGN KEY (rule_version_id) REFERENCES numbering_rule_versions(id),
  FOREIGN KEY (created_by) REFERENCES users(id),
  UNIQUE (part_root_id, purpose_code, sequence_no)
);

CREATE TABLE IF NOT EXISTS drawing_part_links (
  id TEXT PRIMARY KEY,
  drawing_number_id TEXT NOT NULL,
  part_number_id TEXT NOT NULL,
  link_type TEXT NOT NULL CHECK (link_type IN ('primary_manufacturing', 'reference')),
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (drawing_number_id) REFERENCES drawing_numbers(id) ON DELETE CASCADE,
  FOREIGN KEY (part_number_id) REFERENCES part_numbers(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id),
  UNIQUE (drawing_number_id, part_number_id, link_type)
);

CREATE TABLE IF NOT EXISTS same_drawing_variants (
  id TEXT PRIMARY KEY,
  drawing_number_id TEXT NOT NULL,
  part_number_id TEXT NOT NULL,
  field_name TEXT NOT NULL,
  field_value TEXT NOT NULL,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (drawing_number_id) REFERENCES drawing_numbers(id) ON DELETE CASCADE,
  FOREIGN KEY (part_number_id) REFERENCES part_numbers(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id),
  UNIQUE (drawing_number_id, part_number_id, field_name)
);

CREATE TABLE IF NOT EXISTS part_variant_attributes (
  id TEXT PRIMARY KEY,
  part_number_id TEXT NOT NULL UNIQUE,
  material_code TEXT,
  material_label TEXT,
  color_code TEXT,
  color_label TEXT,
  surface_treatment TEXT,
  variant_note TEXT,
  updated_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (part_number_id) REFERENCES part_numbers(id) ON DELETE CASCADE,
  FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS part_cost_profiles (
  id TEXT PRIMARY KEY,
  part_number_id TEXT NOT NULL,
  cost_type TEXT NOT NULL CHECK (cost_type IN ('outsourced', 'in_house', 'purchase', 'trial', 'other')),
  profile_name TEXT NOT NULL,
  currency TEXT NOT NULL DEFAULT 'TWD',
  uom TEXT NOT NULL DEFAULT 'pcs',
  supplier_name TEXT,
  process_name TEXT,
  cost_basis TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'pending_review', 'approved', 'rejected', 'retired')),
  effective_from TEXT,
  effective_to TEXT,
  created_by TEXT,
  approved_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (part_number_id) REFERENCES part_numbers(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (approved_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS part_cost_tiers (
  id TEXT PRIMARY KEY,
  cost_profile_id TEXT NOT NULL,
  min_qty INTEGER NOT NULL DEFAULT 1 CHECK (min_qty > 0),
  max_qty INTEGER CHECK (max_qty IS NULL OR max_qty >= min_qty),
  unit_cost DOUBLE PRECISION NOT NULL CHECK (unit_cost >= 0),
  setup_cost DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (setup_cost >= 0),
  lead_time_days INTEGER CHECK (lead_time_days IS NULL OR lead_time_days >= 0),
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (cost_profile_id) REFERENCES part_cost_profiles(id) ON DELETE CASCADE,
  UNIQUE (cost_profile_id, min_qty)
);

CREATE TABLE IF NOT EXISTS part_standard_costs (
  id TEXT PRIMARY KEY,
  part_number_id TEXT NOT NULL,
  cost_profile_id TEXT NOT NULL,
  basis_qty INTEGER NOT NULL DEFAULT 1 CHECK (basis_qty > 0),
  standard_reason TEXT,
  selected_by TEXT,
  approved_by TEXT,
  effective_from TEXT NOT NULL DEFAULT now(),
  effective_to TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (part_number_id) REFERENCES part_numbers(id) ON DELETE CASCADE,
  FOREIGN KEY (cost_profile_id) REFERENCES part_cost_profiles(id) ON DELETE RESTRICT,
  FOREIGN KEY (selected_by) REFERENCES users(id),
  FOREIGN KEY (approved_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS part_cost_change_requests (
  id TEXT PRIMARY KEY,
  part_number_id TEXT NOT NULL,
  proposed_cost_profile_id TEXT,
  request_type TEXT NOT NULL CHECK (request_type IN ('set_standard', 'update_profile', 'retire_profile')),
  change_reason TEXT NOT NULL,
  review_status TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'approved', 'rejected', 'cancelled')),
  requested_by TEXT,
  reviewed_by TEXT,
  requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reviewed_at TIMESTAMPTZ,
  review_comment TEXT,
  FOREIGN KEY (part_number_id) REFERENCES part_numbers(id) ON DELETE CASCADE,
  FOREIGN KEY (proposed_cost_profile_id) REFERENCES part_cost_profiles(id) ON DELETE SET NULL,
  FOREIGN KEY (requested_by) REFERENCES users(id),
  FOREIGN KEY (reviewed_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS duplicate_check_events (
  id TEXT PRIMARY KEY,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('part_root', 'part_number', 'drawing_number', 'mixed')),
  query_json TEXT NOT NULL DEFAULT '{}',
  result_json TEXT NOT NULL DEFAULT '{}',
  blocked INTEGER NOT NULL DEFAULT 0 CHECK (blocked IN (0, 1)),
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS warning_events (
  id TEXT PRIMARY KEY,
  warning_code TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'warning' CHECK (severity IN ('info', 'warning', 'blocker')),
  entity_type TEXT NOT NULL,
  entity_id TEXT,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  acknowledged_by TEXT,
  acknowledged_at TIMESTAMPTZ,
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (acknowledged_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS numbering_task_items (
  id TEXT PRIMARY KEY,
  task_type TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  risk_level TEXT NOT NULL DEFAULT 'info' CHECK (risk_level IN ('info', 'warning', 'critical')),
  task_status TEXT NOT NULL DEFAULT 'open' CHECK (task_status IN ('open', 'handled', 'cancelled')),
  assigned_to TEXT,
  assigned_role TEXT,
  project_code TEXT,
  action_url TEXT,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  handled_by TEXT,
  handled_at TIMESTAMPTZ,
  FOREIGN KEY (assigned_to) REFERENCES users(id),
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (handled_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS numbering_notifications (
  id TEXT PRIMARY KEY,
  notification_type TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'info' CHECK (severity IN ('info', 'warning', 'critical')),
  recipient_id TEXT,
  recipient_role TEXT,
  read_at TIMESTAMPTZ,
  handled_at TIMESTAMPTZ,
  handled_by TEXT,
  dismissible INTEGER NOT NULL DEFAULT 1 CHECK (dismissible IN (0, 1)),
  action_url TEXT,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (recipient_id) REFERENCES users(id),
  FOREIGN KEY (handled_by) REFERENCES users(id),
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS rule_templates (
  id TEXT PRIMARY KEY,
  template_code TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  template_json TEXT NOT NULL DEFAULT '{}',
  system_defined INTEGER NOT NULL DEFAULT 1 CHECK (system_defined IN (0, 1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS approval_rules (
  id TEXT PRIMARY KEY,
  rule_version_id TEXT NOT NULL,
  rule_name TEXT NOT NULL,
  action_code TEXT NOT NULL,
  phase TEXT,
  record_status TEXT,
  item_kind TEXT,
  risk_flag TEXT,
  requires_approval INTEGER NOT NULL DEFAULT 0 CHECK (requires_approval IN (0, 1)),
  approver_role TEXT,
  blocks_usage INTEGER NOT NULL DEFAULT 0 CHECK (blocks_usage IN (0, 1)),
  blocks_release INTEGER NOT NULL DEFAULT 0 CHECK (blocks_release IN (0, 1)),
  shows_warning INTEGER NOT NULL DEFAULT 1 CHECK (shows_warning IN (0, 1)),
  export_marker INTEGER NOT NULL DEFAULT 1 CHECK (export_marker IN (0, 1)),
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (rule_version_id) REFERENCES numbering_rule_versions(id),
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS approval_requests (
  id TEXT PRIMARY KEY,
  request_type TEXT NOT NULL DEFAULT 'numbering' CHECK (request_type IN ('numbering')),
  action_code TEXT NOT NULL,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('part_root', 'part_number', 'drawing_number', 'same_drawing_variant')),
  entity_id TEXT NOT NULL,
  request_status TEXT NOT NULL DEFAULT 'pending' CHECK (request_status IN ('pending', 'approved', 'rejected', 'needs_info', 'cancelled')),
  reason TEXT NOT NULL,
  payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  requested_by TEXT NOT NULL,
  requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ,
  resolved_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (requested_by) REFERENCES users(id),
  FOREIGN KEY (resolved_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS approval_decisions (
  id TEXT PRIMARY KEY,
  approval_request_id TEXT NOT NULL,
  approver_role TEXT NOT NULL,
  approver_id TEXT NOT NULL,
  decision TEXT NOT NULL CHECK (decision IN ('approved', 'rejected', 'needs_info')),
  comment TEXT,
  decided_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (approval_request_id) REFERENCES approval_requests(id) ON DELETE CASCADE,
  FOREIGN KEY (approver_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS approval_batches (
  id TEXT PRIMARY KEY,
  batch_code TEXT NOT NULL UNIQUE,
  request_type TEXT NOT NULL DEFAULT 'numbering' CHECK (request_type IN ('numbering')),
  project_code TEXT,
  action_code TEXT,
  batch_status TEXT NOT NULL DEFAULT 'pending' CHECK (batch_status IN ('pending', 'partially_approved', 'approved', 'rejected', 'needs_info', 'cancelled')),
  submitted_by TEXT NOT NULL,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (submitted_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS approval_batch_items (
  id TEXT PRIMARY KEY,
  batch_id TEXT NOT NULL,
  approval_request_id TEXT NOT NULL,
  item_status TEXT NOT NULL DEFAULT 'pending' CHECK (item_status IN ('pending', 'approved', 'rejected', 'needs_info', 'cancelled', 'resubmitted')),
  resubmitted_from_item_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (batch_id) REFERENCES approval_batches(id) ON DELETE CASCADE,
  FOREIGN KEY (approval_request_id) REFERENCES approval_requests(id) ON DELETE CASCADE,
  FOREIGN KEY (resubmitted_from_item_id) REFERENCES approval_batch_items(id),
  UNIQUE (batch_id, approval_request_id)
);

CREATE TABLE IF NOT EXISTS roles (
  id TEXT PRIMARY KEY,
  role_code TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  system_defined INTEGER NOT NULL DEFAULT 0 CHECK (system_defined IN (0, 1)),
  enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS role_permissions (
  id TEXT PRIMARY KEY,
  role_id TEXT NOT NULL,
  permission_kind TEXT NOT NULL CHECK (permission_kind IN ('page', 'action')),
  permission_code TEXT NOT NULL,
  allowed INTEGER NOT NULL DEFAULT 1 CHECK (allowed IN (0, 1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
  UNIQUE (role_id, permission_kind, permission_code)
);

CREATE TABLE IF NOT EXISTS role_priority_versions (
  id TEXT PRIMARY KEY,
  version_code TEXT NOT NULL UNIQUE,
  priority_json TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('draft', 'active', 'retired')),
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS role_scope_rules (
  id TEXT PRIMARY KEY,
  role_id TEXT NOT NULL,
  scope_kind TEXT NOT NULL CHECK (scope_kind IN ('department', 'project', 'action')),
  scope_code TEXT NOT NULL,
  allowed INTEGER NOT NULL DEFAULT 1 CHECK (allowed IN (0, 1)),
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id),
  UNIQUE (role_id, scope_kind, scope_code)
);

CREATE TABLE IF NOT EXISTS user_role_assignments (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  role_id TEXT NOT NULL,
  reason TEXT NOT NULL DEFAULT '',
  assigned_by TEXT NOT NULL,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at TIMESTAMPTZ,
  revoked_by TEXT,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
  FOREIGN KEY (assigned_by) REFERENCES users(id),
  FOREIGN KEY (revoked_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS approval_delegations (
  id TEXT PRIMARY KEY,
  delegated_from TEXT NOT NULL,
  delegated_to TEXT NOT NULL,
  project_code TEXT,
  action_code TEXT,
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  reason TEXT NOT NULL,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at TIMESTAMPTZ,
  revoked_by TEXT,
  FOREIGN KEY (delegated_from) REFERENCES users(id),
  FOREIGN KEY (delegated_to) REFERENCES users(id),
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (revoked_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS import_batches (
  id TEXT PRIMARY KEY,
  source_filename TEXT NOT NULL,
  source_hash TEXT,
  status TEXT NOT NULL DEFAULT 'staged' CHECK (status IN ('staged', 'confirmed', 'rejected')),
  summary_json TEXT NOT NULL DEFAULT '{}',
  imported_by TEXT NOT NULL,
  confirmed_by TEXT,
  confirmed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (imported_by) REFERENCES users(id),
  FOREIGN KEY (confirmed_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS import_staging_rows (
  id TEXT PRIMARY KEY,
  import_batch_id TEXT NOT NULL,
  row_no INTEGER NOT NULL CHECK (row_no > 0),
  raw_json TEXT NOT NULL,
  check_status TEXT NOT NULL DEFAULT 'pending' CHECK (check_status IN ('pending', 'valid', 'need_info', 'admin_confirm', 'conflict', 'legacy_keep')),
  issue_json TEXT NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (import_batch_id) REFERENCES import_batches(id) ON DELETE CASCADE,
  UNIQUE (import_batch_id, row_no)
);

CREATE TABLE IF NOT EXISTS file_assets (
  id TEXT PRIMARY KEY,
  storage_provider TEXT NOT NULL DEFAULT 'j_drive' CHECK (storage_provider IN ('j_drive', 'supabase_storage', 'external')),
  original_path TEXT,
  storage_key TEXT,
  file_name TEXT NOT NULL,
  file_ext TEXT NOT NULL DEFAULT '',
  mime_type TEXT,
  file_size BIGINT,
  content_hash TEXT,
  hash_algorithm TEXT NOT NULL DEFAULT 'SHA-256',
  linked_entity_type TEXT NOT NULL,
  linked_entity_id TEXT NOT NULL,
  document_category TEXT NOT NULL DEFAULT 'other',
  display_name TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  revision TEXT,
  uploaded_by TEXT,
  deleted_at TIMESTAMPTZ,
  deleted_by TEXT,
  deleted_reason TEXT,
  gdrive_file_id TEXT,
  gdrive_status TEXT NOT NULL DEFAULT 'none' CHECK (gdrive_status IN ('none', 'uploading', 'uploaded', 'failed')),
  gdrive_error TEXT,
  gdrive_synced_at TIMESTAMPTZ,
  sync_status TEXT NOT NULL DEFAULT 'local_only' CHECK (sync_status IN ('local_only', 'migrated', 'missing', 'hash_mismatch')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS numbering_export_jobs (
  id TEXT PRIMARY KEY,
  export_mode TEXT NOT NULL CHECK (export_mode IN ('no_audit', 'last_change_summary', 'full_change_summary')),
  status TEXT NOT NULL DEFAULT 'completed' CHECK (status IN ('queued', 'running', 'completed', 'failed')),
  result_json TEXT NOT NULL DEFAULT '{}',
  generated_by TEXT,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  FOREIGN KEY (generated_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS monthly_audit_reports (
  id TEXT PRIMARY KEY,
  report_type TEXT NOT NULL,
  report_month TEXT NOT NULL,
  generation_mode TEXT NOT NULL CHECK (generation_mode IN ('auto', 'manual')),
  generated_by TEXT,
  status TEXT NOT NULL DEFAULT 'completed' CHECK (status IN ('queued', 'running', 'completed', 'failed')),
  query_json TEXT NOT NULL DEFAULT '{}',
  scope_json TEXT NOT NULL DEFAULT '{}',
  rule_version_id TEXT,
  download_count INTEGER NOT NULL DEFAULT 0 CHECK (download_count >= 0),
  last_downloaded_by TEXT,
  last_downloaded_at TIMESTAMPTZ,
  regenerate_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (generated_by) REFERENCES users(id),
  FOREIGN KEY (last_downloaded_by) REFERENCES users(id),
  FOREIGN KEY (rule_version_id) REFERENCES numbering_rule_versions(id)
);

CREATE TABLE IF NOT EXISTS llm_conversations (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  title TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS llm_messages (
  id TEXT PRIMARY KEY,
  conversation_id TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (conversation_id) REFERENCES llm_conversations(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_submissions_status_created_at ON submissions(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_submissions_created_at ON submissions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_submissions_submitted_created_at ON submissions(submitted_by, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_submissions_submitted_status_created_at ON submissions(submitted_by, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_submissions_item_created_at ON submissions(item_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_submissions_drawing_number ON submissions(drawing_number);
CREATE INDEX IF NOT EXISTS idx_submissions_finder_fields ON submissions(product_line, customer, project_code, process_name, machine, material, surface_finish, status);
CREATE INDEX IF NOT EXISTS idx_submission_files_submission_id ON submission_files(submission_id);
CREATE INDEX IF NOT EXISTS idx_submission_files_original_filename ON submission_files(original_filename);
CREATE INDEX IF NOT EXISTS idx_file_references_submission_id ON file_references(submission_id);
CREATE INDEX IF NOT EXISTS idx_file_references_referenced_part_number ON file_references(referenced_part_number);
CREATE INDEX IF NOT EXISTS idx_file_references_referenced_drawing_number ON file_references(referenced_drawing_number);
CREATE INDEX IF NOT EXISTS idx_bom_headers_parent_item_id ON bom_headers(parent_item_id);
CREATE INDEX IF NOT EXISTS idx_bom_headers_parent_submission_id ON bom_headers(parent_submission_id);
CREATE INDEX IF NOT EXISTS idx_bom_lines_header_id ON bom_lines(bom_header_id);
CREATE INDEX IF NOT EXISTS idx_bom_lines_child_part_number ON bom_lines(child_part_number);
CREATE INDEX IF NOT EXISTS idx_bom_lines_child_part_revision ON bom_lines(child_part_number, child_revision);
CREATE INDEX IF NOT EXISTS idx_bom_drafts_parent_submission_id ON bom_drafts(parent_submission_id, status, is_active);
CREATE INDEX IF NOT EXISTS idx_bom_drafts_parent_item_revision ON bom_drafts(parent_item_id, parent_revision, status);
CREATE INDEX IF NOT EXISTS idx_bom_lines_tree_draft_parent ON bom_lines_tree(bom_draft_id, parent_line_id, sequence_no);
CREATE INDEX IF NOT EXISTS idx_bom_lines_tree_part_revision ON bom_lines_tree(part_number, revision);
CREATE INDEX IF NOT EXISTS idx_bom_import_jobs_parent_submission_id ON bom_import_jobs(parent_submission_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bom_edit_events_draft_id ON bom_edit_events(bom_draft_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bom_review_requests_draft_status ON bom_review_requests(bom_draft_id, status);
CREATE INDEX IF NOT EXISTS idx_bom_release_snapshots_parent_item_revision ON bom_release_snapshots(parent_item_id, parent_revision, released_at DESC);
CREATE INDEX IF NOT EXISTS idx_item_locks_item_id ON item_locks(item_id, released_at, expires_at);
CREATE INDEX IF NOT EXISTS idx_release_packages_submission_id ON release_packages(submission_id);
CREATE INDEX IF NOT EXISTS idx_readonly_shares_submission_id ON readonly_shares(submission_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_readonly_shares_token_hash ON readonly_shares(token_hash);
CREATE INDEX IF NOT EXISTS idx_supplier_portal_responses_submission_id ON supplier_portal_responses(submission_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supplier_portal_responses_share_id ON supplier_portal_responses(share_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_procurement_sync_runs_submission_id ON procurement_sync_runs(submission_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_procurement_sync_runs_target_status ON procurement_sync_runs(target_system, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sandbox_branches_source_submission_id ON sandbox_branches(source_submission_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sandbox_branches_sandbox_submission_id ON sandbox_branches(sandbox_submission_id);
CREATE INDEX IF NOT EXISTS idx_discussion_comments_submission_id ON discussion_comments(submission_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_discussion_comments_file_id ON discussion_comments(file_id);
CREATE INDEX IF NOT EXISTS idx_review_issues_submission_id ON review_issues(submission_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_review_issues_file_id ON review_issues(file_id);
CREATE INDEX IF NOT EXISTS idx_change_requests_submission_id ON change_requests(submission_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_phase_gate_checks_submission_id ON phase_gate_checks(submission_id, status, gate_code);
CREATE INDEX IF NOT EXISTS idx_approval_matrix_submission_id ON approval_matrix_requirements(submission_id, status, required_role);
CREATE INDEX IF NOT EXISTS idx_pdf_markups_submission_id ON pdf_markups(submission_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pdf_markups_file_id ON pdf_markups(file_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_submission_id ON audit_logs(submission_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_part_roots_status_phase ON part_roots(record_status, development_phase);
CREATE INDEX IF NOT EXISTS idx_part_numbers_root_id ON part_numbers(part_root_id);
CREATE INDEX IF NOT EXISTS idx_part_numbers_status_phase ON part_numbers(record_status, development_phase);
CREATE INDEX IF NOT EXISTS idx_drawing_numbers_root_id ON drawing_numbers(part_root_id);
CREATE INDEX IF NOT EXISTS idx_drawing_numbers_status_phase ON drawing_numbers(record_status, development_phase);
CREATE INDEX IF NOT EXISTS idx_drawing_part_links_drawing_id ON drawing_part_links(drawing_number_id);
CREATE INDEX IF NOT EXISTS idx_same_drawing_variants_part_id ON same_drawing_variants(part_number_id);
CREATE INDEX IF NOT EXISTS idx_part_cost_profiles_part_status ON part_cost_profiles(part_number_id, status);
CREATE INDEX IF NOT EXISTS idx_part_cost_tiers_profile_qty ON part_cost_tiers(cost_profile_id, min_qty);
CREATE INDEX IF NOT EXISTS idx_part_cost_change_requests_part_status ON part_cost_change_requests(part_number_id, review_status, requested_at DESC);
CREATE INDEX IF NOT EXISTS idx_duplicate_check_events_created_at ON duplicate_check_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_warning_events_entity ON warning_events(entity_type, entity_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_warning_events_code ON warning_events(warning_code, severity, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_numbering_task_items_scope ON numbering_task_items(task_status, assigned_role, assigned_to, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_numbering_notifications_scope ON numbering_notifications(recipient_role, recipient_id, read_at, handled_at, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_approval_rules_version_action ON approval_rules(rule_version_id, action_code);
CREATE INDEX IF NOT EXISTS idx_approval_requests_entity ON approval_requests(entity_type, entity_id, request_status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_approval_requests_action ON approval_requests(action_code, request_status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_approval_decisions_request_id ON approval_decisions(approval_request_id, decided_at DESC);
CREATE INDEX IF NOT EXISTS idx_approval_batches_status ON approval_batches(request_type, batch_status, submitted_at DESC);
CREATE INDEX IF NOT EXISTS idx_approval_batch_items_batch_status ON approval_batch_items(batch_id, item_status);
CREATE INDEX IF NOT EXISTS idx_role_permissions_role_id ON role_permissions(role_id);
CREATE INDEX IF NOT EXISTS idx_role_scope_rules_role_kind ON role_scope_rules(role_id, scope_kind);
CREATE INDEX IF NOT EXISTS idx_user_role_assignments_user_active ON user_role_assignments(user_id, revoked_at);
CREATE INDEX IF NOT EXISTS idx_approval_delegations_from_to ON approval_delegations(delegated_from, delegated_to, starts_at, ends_at);
CREATE INDEX IF NOT EXISTS idx_import_staging_rows_batch_status ON import_staging_rows(import_batch_id, check_status);
CREATE INDEX IF NOT EXISTS idx_file_assets_linked_entity ON file_assets(linked_entity_type, linked_entity_id);
CREATE INDEX IF NOT EXISTS idx_numbering_export_jobs_generated ON numbering_export_jobs(export_mode, generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_monthly_audit_reports_month ON monthly_audit_reports(report_type, report_month);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_system_settings_updated_at ON system_settings;
CREATE TRIGGER trg_system_settings_updated_at
BEFORE UPDATE ON system_settings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_items_updated_at ON items;
CREATE TRIGGER trg_items_updated_at
BEFORE UPDATE ON items
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_submissions_updated_at ON submissions;
CREATE TRIGGER trg_submissions_updated_at
BEFORE UPDATE ON submissions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_bom_headers_updated_at ON bom_headers;
CREATE TRIGGER trg_bom_headers_updated_at
BEFORE UPDATE ON bom_headers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_bom_drafts_updated_at ON bom_drafts;
CREATE TRIGGER trg_bom_drafts_updated_at
BEFORE UPDATE ON bom_drafts
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_bom_lines_tree_updated_at ON bom_lines_tree;
CREATE TRIGGER trg_bom_lines_tree_updated_at
BEFORE UPDATE ON bom_lines_tree
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_item_locks_updated_at ON item_locks;
CREATE TRIGGER trg_item_locks_updated_at
BEFORE UPDATE ON item_locks
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_readonly_shares_updated_at ON readonly_shares;
CREATE TRIGGER trg_readonly_shares_updated_at
BEFORE UPDATE ON readonly_shares
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_supplier_portal_responses_updated_at ON supplier_portal_responses;
CREATE TRIGGER trg_supplier_portal_responses_updated_at
BEFORE UPDATE ON supplier_portal_responses
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_procurement_sync_runs_updated_at ON procurement_sync_runs;
CREATE TRIGGER trg_procurement_sync_runs_updated_at
BEFORE UPDATE ON procurement_sync_runs
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_sandbox_branches_updated_at ON sandbox_branches;
CREATE TRIGGER trg_sandbox_branches_updated_at
BEFORE UPDATE ON sandbox_branches
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_discussion_comments_updated_at ON discussion_comments;
CREATE TRIGGER trg_discussion_comments_updated_at
BEFORE UPDATE ON discussion_comments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_review_issues_updated_at ON review_issues;
CREATE TRIGGER trg_review_issues_updated_at
BEFORE UPDATE ON review_issues
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_change_requests_updated_at ON change_requests;
CREATE TRIGGER trg_change_requests_updated_at
BEFORE UPDATE ON change_requests
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_phase_gate_checks_updated_at ON phase_gate_checks;
CREATE TRIGGER trg_phase_gate_checks_updated_at
BEFORE UPDATE ON phase_gate_checks
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_pdf_markups_updated_at ON pdf_markups;
CREATE TRIGGER trg_pdf_markups_updated_at
BEFORE UPDATE ON pdf_markups
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_approval_matrix_requirements_updated_at ON approval_matrix_requirements;
CREATE TRIGGER trg_approval_matrix_requirements_updated_at
BEFORE UPDATE ON approval_matrix_requirements
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_numbering_sequences_updated_at ON numbering_sequences;
CREATE TRIGGER trg_numbering_sequences_updated_at
BEFORE UPDATE ON numbering_sequences
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_numbering_rule_versions_updated_at ON numbering_rule_versions;
CREATE TRIGGER trg_numbering_rule_versions_updated_at
BEFORE UPDATE ON numbering_rule_versions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_part_roots_updated_at ON part_roots;
CREATE TRIGGER trg_part_roots_updated_at
BEFORE UPDATE ON part_roots
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_part_numbers_updated_at ON part_numbers;
CREATE TRIGGER trg_part_numbers_updated_at
BEFORE UPDATE ON part_numbers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_drawing_numbers_updated_at ON drawing_numbers;
CREATE TRIGGER trg_drawing_numbers_updated_at
BEFORE UPDATE ON drawing_numbers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_part_variant_attributes_updated_at ON part_variant_attributes;
CREATE TRIGGER trg_part_variant_attributes_updated_at
BEFORE UPDATE ON part_variant_attributes
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_part_cost_profiles_updated_at ON part_cost_profiles;
CREATE TRIGGER trg_part_cost_profiles_updated_at
BEFORE UPDATE ON part_cost_profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_part_cost_tiers_updated_at ON part_cost_tiers;
CREATE TRIGGER trg_part_cost_tiers_updated_at
BEFORE UPDATE ON part_cost_tiers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_part_standard_costs_updated_at ON part_standard_costs;
CREATE TRIGGER trg_part_standard_costs_updated_at
BEFORE UPDATE ON part_standard_costs
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_numbering_task_items_updated_at ON numbering_task_items;
CREATE TRIGGER trg_numbering_task_items_updated_at
BEFORE UPDATE ON numbering_task_items
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_numbering_notifications_updated_at ON numbering_notifications;
CREATE TRIGGER trg_numbering_notifications_updated_at
BEFORE UPDATE ON numbering_notifications
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_rule_templates_updated_at ON rule_templates;
CREATE TRIGGER trg_rule_templates_updated_at
BEFORE UPDATE ON rule_templates
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_approval_rules_updated_at ON approval_rules;
CREATE TRIGGER trg_approval_rules_updated_at
BEFORE UPDATE ON approval_rules
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_approval_requests_updated_at ON approval_requests;
CREATE TRIGGER trg_approval_requests_updated_at
BEFORE UPDATE ON approval_requests
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_approval_batches_updated_at ON approval_batches;
CREATE TRIGGER trg_approval_batches_updated_at
BEFORE UPDATE ON approval_batches
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_approval_batch_items_updated_at ON approval_batch_items;
CREATE TRIGGER trg_approval_batch_items_updated_at
BEFORE UPDATE ON approval_batch_items
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_roles_updated_at ON roles;
CREATE TRIGGER trg_roles_updated_at
BEFORE UPDATE ON roles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_role_permissions_updated_at ON role_permissions;
CREATE TRIGGER trg_role_permissions_updated_at
BEFORE UPDATE ON role_permissions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_role_scope_rules_updated_at ON role_scope_rules;
CREATE TRIGGER trg_role_scope_rules_updated_at
BEFORE UPDATE ON role_scope_rules
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_import_batches_updated_at ON import_batches;
CREATE TRIGGER trg_import_batches_updated_at
BEFORE UPDATE ON import_batches
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_file_assets_updated_at ON file_assets;
CREATE TRIGGER trg_file_assets_updated_at
BEFORE UPDATE ON file_assets
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_monthly_audit_reports_updated_at ON monthly_audit_reports;
CREATE TRIGGER trg_monthly_audit_reports_updated_at
BEFORE UPDATE ON monthly_audit_reports
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_llm_conversations_updated_at ON llm_conversations;
CREATE TRIGGER trg_llm_conversations_updated_at
BEFORE UPDATE ON llm_conversations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;
